### PR TITLE
Add support for an escape key in mactelnet

### PR DESCRIPTION
**Pull request by xorrkaz**
This is a bit rough, but uses a key "^]" that should be familiar to users as it's the same as telnet (and it shouldn't be used commonly with µT).  I also print it and added it to the pot file.

### CODE REVIEW

**Comment by haakonnessjoen** [comment]
This is not normal behavior for any terminal. But if you are looking for a fast way to disconnect from a shell, you can use CTRL+D in most shells, even RouterOS.

**Comment by xorrkaz** [comment]
I had forgotten about this.  Yeah, this is not the right approach.  I did it in haste.  However, _something_ is needed as Control+D does not work all the time.  Try rebooting a RouterOS device.  You're locked onto the prompt until you close your tab/terminal.  What would you suggest for that?

**Comment by haakonnessjoen** [comment]
It should time out. So if that doesn't happen, then I should be looking a bit at the timeout functionality of the mactelnet client. I will take a look!

**Comment by xorrkaz** [comment]
If it times out, it would take a while (like longer than minute).  Would be nice to quickly (i.e., within a second) recognize an EOF-like condition and exit.  Thanks for looking into it!

**Pull request closed without merging**
