### PR TITLE
Update code for new version gettext and compile on FreeBSD

### PR DESCRIPTION
**Pull request by pautiina**
My change was test on FreeBSD 11 and Centos 7

### CODE REVIEW

**Comment by haakonnessjoen** [comment]
Whats the reason for upping the gettext version?

**Comment by pautiina** [comment]
@haakonnessjoen On FreebSD this is considered the last stable revision, and the previous branch is already problematic to establish.

**Comment by haakonnessjoen** [comment]
But it is only a minimal version requirement. If you have not introduced anything that needs a newer version of gettext, then it would be more safe to let it be. It should happily use the newer stable version in FreeBSD. Unless I am wrong, and you can prove it; it would be really great if you could just remove that change from you pull-request, and I will merge it immediately :)

**Comment by pautiina** [comment]
After change gettext version I have next error:
`*** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.18 but the autoconf macros are from gettext version 0.19`

**Comment by pautiina** [comment]
@haakonnessjoen I have repeated test and install from clean sources and now it's works.

**Pull request merged**
